name: Bug report
description: Report a bug in the codebase
title: ""
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
    validations:
      required: true
      