name: Task Issue
description: A piece of work to be done.
labels: ["task"]
projects: ["SUNDKdk/18"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the task
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: Files
      description: If applicable, attach specs, designs, or other relevant files
    validations:
      required: false
