name: Test / QA Issue
description: A test to be designed or run (manual or automated)
labels: ["test"]
projects: ["SUNDKdk/18"]
body:
  - type: dropdown
    id: test-kind
    attributes:
      label: Kind
      description: Is this a manual test to be described/performed or an automated test to be designed/run?
      options:
        - Manual
        - Automated
        - Both
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what's being tested and why
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope / test cases
      description: What should be covered by the test? List specific cases or scenarios.
      placeholder: |
        - 
        - 
        - 
    validations:
      required: false

  - type: textarea
    id: files
    attributes:
      label: Files
      description: If applicable, attach test scripts, logs, or other relevant files
    validations:
      required: false
